/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShiftTypesRouteImport } from './routes/shift-types'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstructorsRouteImport } from './routes/instructors'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as IndexRouteImport } from './routes/index'

const ShiftTypesRoute = ShiftTypesRouteImport.update({
  id: '/shift-types',
  path: '/shift-types',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsRoute = InstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certifications': typeof CertificationsRoute
  '/departments': typeof DepartmentsRoute
  '/instructors': typeof InstructorsRoute
  '/login': typeof LoginRoute
  '/shift-types': typeof ShiftTypesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certifications': typeof CertificationsRoute
  '/departments': typeof DepartmentsRoute
  '/instructors': typeof InstructorsRoute
  '/login': typeof LoginRoute
  '/shift-types': typeof ShiftTypesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certifications': typeof CertificationsRoute
  '/departments': typeof DepartmentsRoute
  '/instructors': typeof InstructorsRoute
  '/login': typeof LoginRoute
  '/shift-types': typeof ShiftTypesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certifications'
    | '/departments'
    | '/instructors'
    | '/login'
    | '/shift-types'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certifications'
    | '/departments'
    | '/instructors'
    | '/login'
    | '/shift-types'
  id:
    | '__root__'
    | '/'
    | '/certifications'
    | '/departments'
    | '/instructors'
    | '/login'
    | '/shift-types'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificationsRoute: typeof CertificationsRoute
  DepartmentsRoute: typeof DepartmentsRoute
  InstructorsRoute: typeof InstructorsRoute
  LoginRoute: typeof LoginRoute
  ShiftTypesRoute: typeof ShiftTypesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shift-types': {
      id: '/shift-types'
      path: '/shift-types'
      fullPath: '/shift-types'
      preLoaderRoute: typeof ShiftTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificationsRoute: CertificationsRoute,
  DepartmentsRoute: DepartmentsRoute,
  InstructorsRoute: InstructorsRoute,
  LoginRoute: LoginRoute,
  ShiftTypesRoute: ShiftTypesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
